---

- name: Install Erlang
  include_tasks: "install-erlang-{{ ansible_os_family | lower }}.yml"

- name: Install elixir dependencies
  package:
    name: [ 'git', 'esl-erlang', 'elixir' ]
    state: present

- name: Create signaltower directory
  file:
    path: "{{ palava_signaltower_install_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Create signaltower log directory
  file:
    path: "{{ palava_signaltower_log_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Checkout Signltower
  git: 
    repo: 'https://github.com/palavatv/signaltower.git' 
    dest: /srv/signaltower

- name: Install signaltower dependencies
  shell: "cd {{ palava_signaltower_install_dir }} && yes | mix deps.get"

- name: Build Signaltower
  shell: "cd {{ palava_signaltower_install_dir }} && yes | mix deps.compile"

- name: Install Signaltower SystemD unit
  template:
    src: signaltower.service.j2
    dest: /etc/systemd/system/signaltower.service

- name: Start Signaltower
  systemd:
    daemon_reload: yes
    enabled: yes
    name: signaltower.service